# Generated by Django 4.2.11 on 2024-03-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.activity')),
            ],
            options={
                'verbose_name': 'Time Available',
                'verbose_name_plural': 'Times Available',
                'unique_together': {('activity', 'day', 'time')},
            },
        ),
    ]
