# Generated by Django 4.2.11 on 2024-03-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('duration', models.DurationField(default='45 minutes')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Available')], default=0)),
            ],
        ),
    ]
