# Generated by Django 4.2.11 on 2024-03-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.DurationField(),
        ),
    ]
